# NSE Stock symbols - Yahoo Finance format requires .NS suffix
NIFTY_50 = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "INFY.NS", "ICICIBANK.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "KOTAKBANK.NS",
    "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS", "TITAN.NS",
    "SUNPHARMA.NS", "ULTRACEMCO.NS", "BAJFINANCE.NS", "NESTLEIND.NS", "WIPRO.NS",
    "HCLTECH.NS", "POWERGRID.NS", "NTPC.NS", "TECHM.NS", "ONGC.NS",
    "TATASTEEL.NS", "JSWSTEEL.NS", "ADANIENT.NS", "ADANIPORTS.NS", "COALINDIA.NS",
    "DIVISLAB.NS", "DRREDDY.NS", "CIPLA.NS", "EICHERMOT.NS", "BAJAJ-AUTO.NS",
    "HEROMOTOCO.NS", "BPCL.NS", "INDUSINDBK.NS", "BRITANNIA.NS", "GRASIM.NS",
    "TATACONSUM.NS", "M&M.NS", "SBILIFE.NS", "HDFCLIFE.NS", "APOLLOHOSP.NS",
    "TATAMOTOR.NS", "TATAMOTORS.NS", "UPL.NS", "HINDALCO.NS", "SHREECEM.NS"
]

MIDCAP_STOCKS = [
    "PIDILITIND.NS", "MUTHOOTFIN.NS", "GODREJCP.NS", "BERGEPAINT.NS", "DABUR.NS",
    "MARICO.NS", "COLPAL.NS", "HAVELLS.NS", "VOLTAS.NS", "AMBUJACEM.NS",
    "INDIGO.NS", "BALKRISIND.NS", "TRENT.NS", "OFSS.NS", "MPHASIS.NS",
    "LTIM.NS", "PERSISTENT.NS", "COFORGE.NS", "ZOMATO.NS", "NYKAA.NS",
    "POLICYBZR.NS", "PAYTM.NS", "DELHIVERY.NS", "IRCTC.NS", "RVNL.NS",
    "IRFC.NS", "HUDCO.NS", "SJVN.NS", "NHPC.NS", "RECLTD.NS",
    "PFC.NS", "CANBK.NS", "BANKBARODA.NS", "PNB.NS", "UNIONBANK.NS",
    "FEDERALBNK.NS", "RBLBANK.NS", "IDFCFIRSTB.NS", "AUBANK.NS", "CHOLAFIN.NS",
    "MANAPPURAM.NS", "BAJAJFINSV.NS", "LICHSGFIN.NS", "M&MFIN.NS", "SRTRANSFIN.NS"
]

ALL_STOCKS = NIFTY_50 + MIDCAP_STOCKS